version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        APACHE_DOCUMENT_ROOT: ${PROJECT_FOLDER_WEB}
        DOMAIN_HOST_MAIN: ${DOMAIN_HOST_MAIN}
        DOMAIN_HOST_ALIAS: ${DOMAIN_HOST_ALIAS}
    container_name: ${COMPOSE_PROJECT_NAME}-web
    ports:
      - ${PORT_WEB}
    networks:
      vpcpr:
        ipv4_address: ${IP_WEB}
    volumes:
      - project_folder:/var/www/html
    links:
      - mysql
    restart: always

  mysql:
    image: ${MYSQL_VERSION}
    container_name: ${DOCKER_NAME_MYSQL}
    hostname: mysql
    ports:
      - ${PORT_DB}
    networks:
      vpcpr:
        ipv4_address: ${IP_DB}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/conf/disable_strict_mode.cnf:/etc/mysql/conf.d/disable_strict_mode.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_NAME_PHPMYADMIN}
    ports:
      - ${PORT_PMA}
    environment:
      - PMA_HOST=${IP_DB}
    networks:
      vpcpr:
        ipv4_address: ${IP_DBADMIN}
    depends_on:
      - mysql

volumes:
  mysql_data:
  project_folder:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_FOLDER}
networks:
  vpcpr:
    driver: bridge
    ipam:
      config:
        - subnet: ${IP_RANGE}
          gateway: ${IP_GATEWAY}
